var age;
age = 26;
age = true;
age = 'hello';
age = { name: 'luigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('mario');
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: 'mario', age: 25 };
console.log(ninja);
ninja = { name: 25, age: 'mario' };
console.log(ninja);
